import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { FiArrowLeft, FiCopy, FiEdit2, FiLink, FiSave, FiTrash2, FiX } from 'react-icons/fi';
import { api, authHeaders } from '../api';
import { useAuth } from '../contexts/AuthContext';

export default function NoteView() {
  const { id } = useParams(); const navigate = useNavigate(); const { token } = useAuth();
  const [note, setNote] = useState(null); const [draft, setDraft] = useState(null); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [share, setShare] = useState({ shareType: 'time-based', accessType: 'public', expiresIn: '60' }); const [shareResult, setShareResult] = useState(null);
  useEffect(() => { let active = true; api(`/notes/${id}`, { headers: authHeaders(token) }).then((data) => { if (active) { setNote(data); setDraft({ title: data.title, content: data.content }); } }).catch((err) => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id, token]);
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const updated = await api(`/notes/${id}`, { method: 'PUT', headers: authHeaders(token), body: JSON.stringify(draft) }); setNote(updated); setEditing(false); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const remove = async () => { if (!window.confirm('Delete this note permanently?')) return; try { await api(`/notes/${id}`, { method: 'DELETE', headers: authHeaders(token) }); navigate('/notes'); } catch (err) { setError(err.message); } };
  const createShare = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { setShareResult(await api(`/notes/${id}/share`, { method: 'POST', headers: authHeaders(token), body: JSON.stringify(share) })); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const revoke = async () => { try { await api(`/notes/${id}/share`, { method: 'DELETE', headers: authHeaders(token) }); setShareResult(null); } catch (err) { setError(err.message); } };
  const copy = async (value) => { try { await navigator.clipboard.writeText(value); } catch { setError('Could not copy to your clipboard.'); } };
  if (loading) return <main className="page"><p className="muted">Loading your note...</p></main>;
  if (!note) return <main className="page"><p className="alert">{error || 'Note not found.'}</p><button className="button ghost" onClick={() => navigate('/notes')}>Back to notes</button></main>;
  const shareUrl = shareResult && `${window.location.origin}/share/${shareResult.shareToken}`;
  return <main className="page"><button className="button ghost" onClick={() => navigate('/notes')}><FiArrowLeft /> All notes</button><div className="detail-grid" style={{ marginTop: 22 }}><section className="panel">{error && <p className="alert">{error}</p>}{editing ? <form className="form-stack" onSubmit={save}><label>Title<input required value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label>Content<textarea required value={draft.content} onChange={(e) => setDraft({ ...draft, content: e.target.value })} /></label><div className="actions"><button className="button" disabled={saving}><FiSave /> {saving ? 'Saving...' : 'Save changes'}</button><button type="button" className="button ghost" onClick={() => { setDraft({ title: note.title, content: note.content }); setEditing(false); }}><FiX /> Cancel</button></div></form> : <><div className="page-head"><div><p className="eyebrow">Updated {new Date(note.updatedAt).toLocaleString()}</p><h1>{note.title}</h1></div><div className="actions"><button className="button ghost" onClick={() => setEditing(true)}><FiEdit2 /> Edit</button><button className="button danger" title="Delete note" onClick={remove}><FiTrash2 /></button></div></div><article className="note-content">{note.content}</article></>}</section><aside className="sidebar"><section className="panel"><h2><FiLink /> Share access</h2><p className="muted">Create a deliberate, expiring access link.</p><form className="form-stack" onSubmit={createShare}><label>Access window<select value={share.shareType} onChange={(e) => setShare({ ...share, shareType: e.target.value })}><option value="time-based">Expires after a time</option><option value="one-time">One successful view</option></select></label>{share.shareType === 'time-based' && <label>Expires in (minutes)<input type="number" min="1" value={share.expiresIn} onChange={(e) => setShare({ ...share, expiresIn: e.target.value })} /></label>}<label>Protection<select value={share.accessType} onChange={(e) => setShare({ ...share, accessType: e.target.value })}><option value="public">Anyone with the link</option><option value="password-protected">Password required</option></select></label><button className="button" disabled={saving}>{saving ? 'Creating...' : 'Create secure link'}</button></form>{shareResult && <div className="share-result"><strong>Link ready</strong><code>{shareUrl}</code><button className="button secondary" onClick={() => copy(shareUrl)}><FiCopy /> Copy link</button>{shareResult.sharePassword && <><p>Password (shown once):</p><code>{shareResult.sharePassword}</code><button className="button ghost" onClick={() => copy(shareResult.sharePassword)}><FiCopy /> Copy password</button></>}<p className="muted">{shareResult.expiresAt ? `Expires ${new Date(shareResult.expiresAt).toLocaleString()}` : 'Available for one successful view.'}</p><button className="button danger" onClick={revoke}>Revoke link</button></div>}</section></aside></div></main>;
}
